### ISSUE TITLE
Consider adding an interface method for receiving data to Transport

### ISSUE THREAD

**Issue by vkomenda** [Fantom-foundation/libtransport#3]
Receive functionality could be implemented as a `Future`

This is an off-shoot of the review https://github.com/Fantom-foundation/libtransport/pull/2. Without a  `receive` method, the `Transport` trait API is incomplete and likely unnecessary if receiving messages is going to be implemented without using this API.

**Comment by Maxime2** [comment]
Receiving method is implemented as `Stream`, see  https://rust-lang.github.io/async-book/05_streams/01_chapter.html and https://rust-lang.github.io/async-book/05_streams/01_chapter.html

It should be clear from common_test() that receiving method is implemented (https://github.com/Fantom-foundation/libtransport/blob/8103117e1fb6b1fac3eac5ea348f0634dd67e551/src/generic_test.rs#L112) and current status of `libtransport-tcp` repo shows it works.
